CC = gcc 
CFLAGS = -Wall -Werror -Wextra
STANDART = -std=c11

all: state_sort state_search clear_state

state_sort:
	$(CC) $(CFLAGS) $(STANDART) state_sort.c date.c -o ../build/Quest_1

state_search:
	$(CC) $(CFLAGS) $(STANDART) state_search.c -o ../build/Quest_2

clear_state:
	$(CC) $(CFLAGS) $(STANDART) clear_state.c date.c -o ../build/Quest_3
